language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
    - composer install --dev

script:
    #- phpunit --configuration phpunit.xml.dist
    #- bin/phpspec run

matrix:
    allow_failures:
        - php: 5.6
        - php: hhvm # expirimental
        - php: hhvm-nightly
