language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: 7.1
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - composer install -o

script:
    - vendor/bin/phpspec run
